version: '3.8'

services:
  springboot-app:
    container_name: book_store_app
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_REDIS_HOST: redis
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - ./:/app
    networks:
      - app-network
    command: ["./mvnw", "spring-boot:run"]

  redis:
    image: redis:latest
    container_name: book_store_redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  redis-data: